name: 🚀 Deploy to Cloudways
on:
  push:
    branches:
      - master
      
jobs:
  deploy-job:
    name: SFTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: 📂 Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: 178.62.83.164
        username: tap_admin123
        password: Tap_admin123
        local_path: './*'
        remote_path: '/'
        sftpArgs: '-v -o ConnectTimeout=5'
      
    
